#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# TunAgri — one-shot bootstrap for a fresh VPS.
#
# Does everything from scratch:
#   1. Asks for the few values only YOU know (Cloudinary, Atlas URI…)
#   2. Generates strong secrets automatically (Mongo password, JWT)
#   3. Writes a valid .env.production with correct quoting
#   4. Patches scripts/deploy.sh to use --env-file (idempotent)
#   5. Wipes any half-initialized Mongo volumes
#   6. Deploys the stack (mongo + web + caddy)
#   7. Migrates Atlas → local Mongo if you provided an Atlas URI
#
# Usage:
#   cd ~/apps/tunagri
#   ./scripts/bootstrap.sh
#
# Safe to re-run — backs up any existing .env.production first.
# ─────────────────────────────────────────────────────────────
set -Eeuo pipefail

cd "$(dirname "$0")/.."
REPO_DIR="$(pwd)"

echo "═══════════════════════════════════════════════════════════"
echo "  TunAgri — bootstrap"
echo "═══════════════════════════════════════════════════════════"
echo ""

# ── 1. Interactive prompts (with sensible defaults) ──────────
read -r -p "Domain [tunagri.com]: " DOMAIN
DOMAIN="${DOMAIN:-tunagri.com}"

read -r -p "ACME email for Let's Encrypt [admin@$DOMAIN]: " ACME_EMAIL
ACME_EMAIL="${ACME_EMAIL:-admin@$DOMAIN}"

echo ""
echo "→ Cloudinary credentials (Dashboard → Settings → API keys)"
read -r -p "  CLOUDINARY_CLOUD_NAME: " CLOUDINARY_CLOUD_NAME
read -r -p "  CLOUDINARY_API_KEY: "    CLOUDINARY_API_KEY
read -r -s -p "  CLOUDINARY_API_SECRET (hidden): " CLOUDINARY_API_SECRET
echo

echo ""
echo "→ MongoDB Atlas — paste your current connection string to MIGRATE existing data."
echo "  Get it from Atlas → your cluster → Connect → Drivers → Node.js."
echo "  Leave BLANK to start with an empty local database."
read -r -p "  ATLAS_URI: " ATLAS_URI

# ── 2. Auto-generated secrets ────────────────────────────────
MONGO_ROOT_USER="tunagri_admin"
MONGO_ROOT_PASSWORD="$(openssl rand -hex 24)"
NEXTAUTH_SECRET="$(openssl rand -base64 48)"
MONGODB_URI="mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/tunagri?authSource=admin"

echo ""
echo "→ Generated a random 48-char Mongo root password and 64-char JWT secret."

# ── 3. Backup any existing .env.production ───────────────────
if [[ -f .env.production ]]; then
    BACKUP=".env.production.bak.$(date +%Y%m%d-%H%M%S)"
    cp .env.production "$BACKUP"
    echo "→ Backed up existing .env.production → $BACKUP"
fi

# ── 4. Write .env.production ─────────────────────────────────
# All values are single-quoted so shell never tries to interpret $ or `.
cat > .env.production <<ENVEOF
# ============================================================
# Auto-generated by scripts/bootstrap.sh on $(date -Is)
# ============================================================

# ── Domain / TLS ────────────────────────────────────────────
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL

# ── App ─────────────────────────────────────────────────────
NODE_ENV=production
NEXT_PUBLIC_APP_URL=https://$DOMAIN

# ── MongoDB (local Docker) ──────────────────────────────────
MONGO_ROOT_USER=$MONGO_ROOT_USER
MONGO_ROOT_PASSWORD='$MONGO_ROOT_PASSWORD'
MONGODB_URI='$MONGODB_URI'

# ── Auth / JWT ──────────────────────────────────────────────
NEXTAUTH_SECRET='$NEXTAUTH_SECRET'
NEXTAUTH_URL=https://$DOMAIN

# ── Cloudinary ──────────────────────────────────────────────
CLOUDINARY_CLOUD_NAME='$CLOUDINARY_CLOUD_NAME'
CLOUDINARY_API_KEY='$CLOUDINARY_API_KEY'
CLOUDINARY_API_SECRET='$CLOUDINARY_API_SECRET'

# ── One-time: Atlas connection string (for migration only) ──
ATLAS_URI='$ATLAS_URI'
ENVEOF

chmod 600 .env.production
echo "→ Wrote .env.production (chmod 600)"

# ── 5. Patch deploy.sh (idempotent) ──────────────────────────
if ! grep -q -- "--env-file" scripts/deploy.sh; then
    sed -i 's|docker compose -f "\$COMPOSE_FILE"|docker compose --env-file .env.production -f "$COMPOSE_FILE"|g' scripts/deploy.sh
    echo "→ Patched scripts/deploy.sh with --env-file .env.production"
fi
chmod +x scripts/*.sh

# ── 6. Wipe broken Mongo (may have been init'd with empty pw) ─
echo ""
echo "→ Stopping any running stack and wiping Mongo volumes for a clean init..."
docker compose --env-file .env.production -f docker-compose.prod.yml down --remove-orphans || true
docker volume rm tunagri_mongo_data tunagri_mongo_config 2>/dev/null || true

# ── 7. Deploy fresh ──────────────────────────────────────────
echo ""
echo "→ Deploying stack..."
./scripts/deploy.sh --no-pull

# ── 8. Migrate if Atlas URI was provided ─────────────────────
if [[ -n "$ATLAS_URI" ]]; then
    echo ""
    echo "→ Running Atlas → local migration..."
    if ! ./scripts/migrate-from-atlas.sh; then
        echo ""
        echo "⚠ Migration failed. Common causes:"
        echo "    • Your VPS IP (135.125.175.108) isn't in the Atlas Network Access allowlist."
        echo "    • The Atlas URI has a wrong username/password."
        echo "  Fix, then re-run:  ./scripts/migrate-from-atlas.sh"
    fi
else
    echo ""
    echo "  Skipped Atlas migration (ATLAS_URI was blank)."
    echo "  Your local Mongo is empty. You'll create the first admin user via the app's UI."
fi

# ── 9. Final status ──────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
docker compose --env-file .env.production -f docker-compose.prod.yml ps
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✓ Bootstrap complete."
echo "  Visit: https://$DOMAIN"
echo ""
echo "  Watch logs:      docker compose --env-file .env.production -f docker-compose.prod.yml logs -f"
echo "  Set up backups:  crontab -e   →   0 3 * * *  $REPO_DIR/scripts/backup-mongo.sh >> ~/mongo-backup.log 2>&1"
